#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --remove name --hostname name "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --remove name --hostname name "$@"

fi

