#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/libexec/device-set --set name --hostname name --text authentication-password --select-base /usr/libexec/device/services/snmp/authentication-protocols.txt --select authentication-protocol --text encryption-password --select-base /usr/libexec/device/services/snmp/encryption-protocols.txt --select encryption-protocol --select-base /usr/libexec/device/services/snmp/security-models.txt --select security-model "$@"

  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd-autodiscovery.service
  /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd.service

elif [ "$1" == "-c" ]; then

  /usr/libexec/device-set --set name --hostname name --text authentication-password --select-base /usr/libexec/device/services/snmp/authentication-protocols.txt --select authentication-protocol --text encryption-password --select-base /usr/libexec/device/services/snmp/encryption-protocols.txt --select encryption-protocol --select-base /usr/libexec/device/services/snmp/security-models.txt --select security-model "$@"

fi

