#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  if test -f "enabled"; then
    echo "tls is already enabled."
  elif test -f "disabled"; then
    mv "disabled" "enabled"
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd.service
  else
    touch "enabled"
    echo "tls will be enabled on next reboot."
  fi

fi

