#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  if test -f "disabled"; then
    echo "ssh is already disabled."
  elif test -f "enabled"; then
    mv "enabled" "disabled"
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd-autodiscovery.service
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart snmpd.service
    /usr/bin/sudo /usr/bin/systemctl try-reload-or-restart sshd.service
  fi

fi

